import { KeywordRule } from '../types';
import { CATEGORIES } from '../categories';

export const KEYWORD_RULES: KeywordRule[] = [
  { keyword: 'payroll', category: CATEGORIES.payroll },
  { keyword: 'salary', category: CATEGORIES.payroll },
  { keyword: 'wages', category: CATEGORIES.payroll },
  { keyword: 'rent', category: CATEGORIES.rent },
  { keyword: 'lease', category: CATEGORIES.rent },
  { keyword: 'electric', category: CATEGORIES.utilities },
  { keyword: 'gas bill', category: CATEGORIES.utilities },
  { keyword: 'water bill', category: CATEGORIES.utilities },
  { keyword: 'internet', category: CATEGORIES.utilities },
  { keyword: 'phone', category: CATEGORIES.utilities },
  { keyword: 'insurance', category: CATEGORIES.insurance },
  { keyword: 'premium', category: CATEGORIES.insurance },
  { keyword: 'legal', category: CATEGORIES.professional_services },
  { keyword: 'attorney', category: CATEGORIES.professional_services },
  { keyword: 'lawyer', category: CATEGORIES.professional_services },
  { keyword: 'accounting', category: CATEGORIES.professional_services },
  { keyword: 'consulting', category: CATEGORIES.professional_services },
  { keyword: 'tax', category: CATEGORIES.taxes },
  { keyword: 'irs', category: CATEGORIES.taxes },
  { keyword: 'advertising', category: CATEGORIES.advertising },
  { keyword: 'marketing', category: CATEGORIES.advertising },
  { keyword: 'hotel', category: CATEGORIES.travel },
  { keyword: 'flight', category: CATEGORIES.travel },
  { keyword: 'airline', category: CATEGORIES.travel },
  { keyword: 'parking', category: CATEGORIES.travel },
  { keyword: 'restaurant', category: CATEGORIES.meals },
  { keyword: 'catering', category: CATEGORIES.meals },
  { keyword: 'lunch', category: CATEGORIES.meals },
  { keyword: 'dinner', category: CATEGORIES.meals },
  { keyword: 'coffee', category: CATEGORIES.meals },
  { keyword: 'subscription', category: CATEGORIES.subscriptions },
  { keyword: 'membership', category: CATEGORIES.subscriptions },
  { keyword: 'shipping', category: CATEGORIES.shipping },
  { keyword: 'freight', category: CATEGORIES.shipping },
  { keyword: 'postage', category: CATEGORIES.shipping },
  { keyword: 'donation', category: CATEGORIES.charitable },
  { keyword: 'charity', category: CATEGORIES.charitable },
  { keyword: 'bank fee', category: CATEGORIES.bank_fees },
  { keyword: 'service charge', category: CATEGORIES.bank_fees },
  { keyword: 'overdraft', category: CATEGORIES.bank_fees },
  { keyword: 'wire fee', category: CATEGORIES.bank_fees },
];
