import { MccMapping } from '../types';
import { CATEGORIES } from '../categories';

const C = CATEGORIES;

export const MCC_MAPPINGS: MccMapping[] = [
  { code: '5411', description: 'Grocery Stores, Supermarkets', category: C.groceries },
  { code: '5422', description: 'Freezer and Locker Meat Provisioners', category: C.groceries },
  { code: '5441', description: 'Candy, Nut, Confectionery Stores', category: C.groceries },
  { code: '5451', description: 'Dairy Products Stores', category: C.groceries },
  { code: '5462', description: 'Bakeries', category: C.groceries },
  { code: '5499', description: 'Miscellaneous Food Stores', category: C.groceries },
  { code: '5812', description: 'Eating Places, Restaurants', category: C.meals },
  { code: '5813', description: 'Bars, Cocktail Lounges, Nightclubs', category: C.meals },
  { code: '5814', description: 'Fast Food Restaurants', category: C.meals },
  { code: '4121', description: 'Taxicabs and Rideshares', category: C.transportation },
  { code: '4111', description: 'Local/Suburban Commuter Transportation', category: C.transportation },
  { code: '4112', description: 'Passenger Railways', category: C.transportation },
  { code: '4131', description: 'Bus Lines', category: C.transportation },
  { code: '4784', description: 'Tolls and Bridge Fees', category: C.transportation },
  { code: '7512', description: 'Car Rental Agencies', category: C.transportation },
  { code: '5541', description: 'Service Stations (Gas)', category: C.transportation },
  { code: '5542', description: 'Automated Fuel Dispensers', category: C.transportation },
  { code: '4789', description: 'Transportation Services', category: C.transportation },
  { code: '3000', description: 'Airlines (United)', category: C.travel },
  { code: '3001', description: 'Airlines (American)', category: C.travel },
  { code: '3005', description: 'Airlines (British Airways)', category: C.travel },
  { code: '3007', description: 'Airlines (Air France)', category: C.travel },
  { code: '3009', description: 'Airlines (Continental)', category: C.travel },
  { code: '3014', description: 'Airlines (Delta)', category: C.travel },
  { code: '3026', description: 'Airlines (JetBlue)', category: C.travel },
  { code: '3031', description: 'Airlines (Southwest)', category: C.travel },
  { code: '3032', description: 'Airlines (Alaska)', category: C.travel },
  { code: '3058', description: 'Airlines (Spirit)', category: C.travel },
  { code: '3068', description: 'Airlines (Frontier)', category: C.travel },
  { code: '4511', description: 'Airlines, Air Carriers', category: C.travel },
  { code: '3501', description: 'Hotels (Hilton)', category: C.travel },
  { code: '3502', description: 'Hotels (Sheraton)', category: C.travel },
  { code: '3503', description: 'Hotels (Best Western)', category: C.travel },
  { code: '3504', description: 'Hotels (Holiday Inn)', category: C.travel },
  { code: '3509', description: 'Hotels (Marriott)', category: C.travel },
  { code: '3512', description: 'Hotels (InterContinental)', category: C.travel },
  { code: '3515', description: 'Hotels (Fairmont)', category: C.travel },
  { code: '3522', description: 'Hotels (Hyatt)', category: C.travel },
  { code: '3527', description: 'Hotels (Ramada)', category: C.travel },
  { code: '3533', description: 'Hotels (Radisson)', category: C.travel },
  { code: '7011', description: 'Lodging - Hotels, Motels, Resorts', category: C.travel },
  { code: '4722', description: 'Travel Agencies', category: C.travel },
  { code: '5111', description: 'Stationery, Office Supplies', category: C.office_supplies },
  { code: '5943', description: 'Stationery Stores', category: C.office_supplies },
  { code: '2741', description: 'Miscellaneous Publishing and Printing', category: C.office_supplies },
  { code: '5112', description: 'Stationery and Office Supplies Wholesale', category: C.office_supplies },
  { code: '5192', description: 'Books, Periodicals, and Newspapers', category: C.office_supplies },
  { code: '5734', description: 'Computer Software Stores', category: C.software },
  { code: '5045', description: 'Computers and Computer Peripherals', category: C.software },
  { code: '7372', description: 'Computer Programming, Data Processing', category: C.software },
  { code: '5817', description: 'Digital Goods: Software Applications', category: C.software },
  { code: '5818', description: 'Digital Goods: Large Digital Goods Merchant', category: C.software },
  { code: '5816', description: 'Digital Goods: Games', category: C.software },
  { code: '5732', description: 'Electronic Sales', category: C.equipment },
  { code: '5733', description: 'Music Stores', category: C.equipment },
  { code: '5946', description: 'Camera and Photographic Supply Stores', category: C.equipment },
  { code: '5044', description: 'Photocopy, Photographic, Microfilm Equipment', category: C.equipment },
  { code: '5251', description: 'Hardware Stores', category: C.equipment },
  { code: '5065', description: 'Electrical Parts and Equipment', category: C.equipment },
  { code: '5021', description: 'Office and Commercial Furniture', category: C.equipment },
  { code: '5046', description: 'Commercial Equipment', category: C.equipment },
  { code: '5047', description: 'Medical and Dental Equipment', category: C.equipment },
  { code: '6300', description: 'Insurance Sales, Underwriting', category: C.insurance },
  { code: '6381', description: 'Insurance Premiums', category: C.insurance },
  { code: '6399', description: 'Insurance - Not Elsewhere Classified', category: C.insurance },
  { code: '5960', description: 'Direct Marketing - Insurance', category: C.insurance },
  { code: '8111', description: 'Legal Services, Attorneys', category: C.professional_services },
  { code: '8931', description: 'Accounting, Auditing, Bookkeeping', category: C.professional_services },
  { code: '8999', description: 'Professional Services - NEC', category: C.professional_services },
  { code: '8742', description: 'Management Consulting Services', category: C.professional_services },
  { code: '8734', description: 'Testing Laboratories', category: C.professional_services },
  { code: '7392', description: 'Management, Consulting, PR Services', category: C.professional_services },
  { code: '8011', description: 'Doctors', category: C.professional_services },
  { code: '8021', description: 'Dentists, Orthodontists', category: C.professional_services },
  { code: '8049', description: 'Chiropodists, Podiatrists', category: C.professional_services },
  { code: '8050', description: 'Nursing and Personal Care Facilities', category: C.professional_services },
  { code: '7311', description: 'Advertising Services', category: C.advertising },
  { code: '7312', description: 'Outdoor Advertising Services', category: C.advertising },
  { code: '7319', description: 'Miscellaneous Advertising Services', category: C.advertising },
  { code: '7331', description: 'Mailing, Reproduction, Stenographic', category: C.advertising },
  { code: '4812', description: 'Telecommunication Equipment', category: C.utilities },
  { code: '4813', description: 'Telephone Services', category: C.utilities },
  { code: '4814', description: 'Fax Services', category: C.utilities },
  { code: '4816', description: 'Computer Network/Information Services', category: C.utilities },
  { code: '4821', description: 'Telegraph Services', category: C.utilities },
  { code: '4899', description: 'Cable, Satellite, Pay Television', category: C.utilities },
  { code: '4900', description: 'Utilities - Electric, Gas, Water, Sanitary', category: C.utilities },
  { code: '6010', description: 'Financial Institutions - Manual Cash', category: C.bank_fees },
  { code: '6011', description: 'Financial Institutions - Automated Cash', category: C.bank_fees },
  { code: '6012', description: 'Financial Institutions - Merchandise', category: C.bank_fees },
  { code: '6051', description: 'Non-FI Money Orders', category: C.bank_fees },
  { code: '6211', description: 'Security Brokers/Dealers', category: C.bank_fees },
  { code: '6050', description: 'Quasi Cash - Financial Institutions', category: C.bank_fees },
  { code: '9211', description: 'Court Costs, Fines', category: C.taxes },
  { code: '9222', description: 'Fines', category: C.taxes },
  { code: '9311', description: 'Tax Payments', category: C.taxes },
  { code: '9399', description: 'Government Services', category: C.taxes },
  { code: '9405', description: 'Intra-Government Purchases', category: C.taxes },
  { code: '4215', description: 'Courier Services', category: C.shipping },
  { code: '4225', description: 'Public Warehousing, Storage', category: C.shipping },
  { code: '9402', description: 'Postal Services - Government Only', category: C.shipping },
  { code: '7941', description: 'Athletic Clubs, Sports Clubs', category: C.subscriptions },
  { code: '8641', description: 'Civic, Social, Fraternal Associations', category: C.subscriptions },
  { code: '8651', description: 'Political Organizations', category: C.subscriptions },
  { code: '8699', description: 'Membership Organizations', category: C.subscriptions },
  { code: '8661', description: 'Religious Organizations', category: C.charitable },
  { code: '8398', description: 'Charitable and Social Service Organizations', category: C.charitable },
  { code: '5013', description: 'Motor Vehicle Supplies Wholesale', category: C.inventory },
  { code: '5039', description: 'Construction Materials', category: C.inventory },
  { code: '5051', description: 'Metal Service Centers and Offices', category: C.inventory },
  { code: '5072', description: 'Hardware Equipment and Supplies', category: C.inventory },
  { code: '5085', description: 'Industrial Supplies', category: C.inventory },
  { code: '5094', description: 'Precious Stones and Metals', category: C.inventory },
  { code: '5099', description: 'Durable Goods', category: C.inventory },
  { code: '5131', description: 'Piece Goods, Notions, Dry Goods', category: C.inventory },
  { code: '5137', description: 'Uniforms and Commercial Clothing', category: C.inventory },
  { code: '5139', description: 'Commercial Footwear', category: C.inventory },
  { code: '5169', description: 'Chemicals and Allied Products', category: C.inventory },
  { code: '5193', description: 'Florists Supplies, Nursery Stock', category: C.inventory },
  { code: '5198', description: 'Paints, Varnishes, and Supplies', category: C.inventory },
  { code: '5199', description: 'Nondurable Goods', category: C.inventory },
  { code: '6513', description: 'Real Estate Agents - Rentals', category: C.rent },
  { code: '1520', description: 'General Contractors - Residential', category: C.rent },
  { code: '1711', description: 'Heating, Plumbing, AC Contractors', category: C.utilities },
  { code: '1731', description: 'Electrical Contractors', category: C.utilities },
  { code: '1740', description: 'Masonry, Stonework, Tile', category: C.rent },
  { code: '1750', description: 'Carpentry Contractors', category: C.rent },
  { code: '1761', description: 'Roofing, Siding, Sheet Metal', category: C.rent },
  { code: '1799', description: 'Special Trade Contractors', category: C.rent },
  { code: '7361', description: 'Employment Agencies, Temp Help', category: C.payroll },
];

const mccMap = new Map<string, MccMapping>();
for (const mapping of MCC_MAPPINGS) {
  mccMap.set(mapping.code, mapping);
}

export function lookupMcc(code: string): MccMapping | undefined {
  return mccMap.get(code);
}

export const MCC_CODES = MCC_MAPPINGS;
