import { MerchantPattern } from '../types';
import { CATEGORIES } from '../categories';

const C = CATEGORIES;

export const MERCHANT_PATTERNS: MerchantPattern[] = [
  { pattern: /\bUBER\b/i, merchant: 'Uber', category: C.transportation },
  { pattern: /\bLYFT\b/i, merchant: 'Lyft', category: C.transportation },
  { pattern: /\bGRAB\b/i, merchant: 'Grab', category: C.transportation },
  { pattern: /\bSTARBUCKS\b/i, merchant: 'Starbucks', category: C.meals },
  { pattern: /\bMCDONALD/i, merchant: "McDonald's", category: C.meals },
  { pattern: /\bCHIPOTLE\b/i, merchant: 'Chipotle', category: C.meals },
  { pattern: /\bSUBWAY\b/i, merchant: 'Subway', category: C.meals },
  { pattern: /\bDOMINO/i, merchant: "Domino's", category: C.meals },
  { pattern: /\bPANERA\b/i, merchant: 'Panera Bread', category: C.meals },
  { pattern: /\bCHICK-?FIL-?A/i, merchant: 'Chick-fil-A', category: C.meals },
  { pattern: /\bDUNKIN/i, merchant: "Dunkin'", category: C.meals },
  { pattern: /\bWENDY/i, merchant: "Wendy's", category: C.meals },
  { pattern: /\bTACO\s*BELL/i, merchant: 'Taco Bell', category: C.meals },
  { pattern: /\bBURGER\s*KING/i, merchant: 'Burger King', category: C.meals },
  { pattern: /\bDOORDASH\b/i, merchant: 'DoorDash', category: C.meals },
  { pattern: /\bGRUBHUB\b/i, merchant: 'Grubhub', category: C.meals },
  { pattern: /\bUBER\s*EATS/i, merchant: 'Uber Eats', category: C.meals },
  { pattern: /\bPIZZA\s*HUT/i, merchant: 'Pizza Hut', category: C.meals },
  { pattern: /\bAMZN\b|AMAZON/i, merchant: 'Amazon', category: C.office_supplies },
  { pattern: /\bSTAPLES\b/i, merchant: 'Staples', category: C.office_supplies },
  { pattern: /\bOFFICE\s*DEPOT/i, merchant: 'Office Depot', category: C.office_supplies },
  { pattern: /\bOFFICE\s*MAX/i, merchant: 'OfficeMax', category: C.office_supplies },
  { pattern: /\bGOOGLE\b(?!.*(?:ADS|ADWORDS))/i, merchant: 'Google', category: C.software },
  { pattern: /\bMICROSOFT\b|MSFT/i, merchant: 'Microsoft', category: C.software },
  { pattern: /\bAPPLE\.COM|APPLE\s*STORE/i, merchant: 'Apple', category: C.software },
  { pattern: /\bSLACK\b/i, merchant: 'Slack', category: C.software },
  { pattern: /\bZOOM\b/i, merchant: 'Zoom', category: C.software },
  { pattern: /\bDROPBOX\b/i, merchant: 'Dropbox', category: C.software },
  { pattern: /\bATLASSIAN\b|JIRA|CONFLUENCE/i, merchant: 'Atlassian', category: C.software },
  { pattern: /\bGITHUB\b/i, merchant: 'GitHub', category: C.software },
  { pattern: /\bNOTION\b/i, merchant: 'Notion', category: C.software },
  { pattern: /\bFIGMA\b/i, merchant: 'Figma', category: C.software },
  { pattern: /\bADOBE\b/i, merchant: 'Adobe', category: C.software },
  { pattern: /\bSALESFORCE\b/i, merchant: 'Salesforce', category: C.software },
  { pattern: /\bHUBSPOT\b/i, merchant: 'HubSpot', category: C.software },
  { pattern: /\bAWS\b|AMAZON\s*WEB/i, merchant: 'AWS', category: C.software },
  { pattern: /\bHEROKU\b/i, merchant: 'Heroku', category: C.software },
  { pattern: /\bVERCEL\b/i, merchant: 'Vercel', category: C.software },
  { pattern: /\bNETLIFY\b/i, merchant: 'Netlify', category: C.software },
  { pattern: /\bDIGITAL\s*OCEAN/i, merchant: 'DigitalOcean', category: C.software },
  { pattern: /\bTWILIO\b/i, merchant: 'Twilio', category: C.software },
  { pattern: /\bSENDGRID\b/i, merchant: 'SendGrid', category: C.software },
  { pattern: /\bSTRIPE\b/i, merchant: 'Stripe', category: C.software },
  { pattern: /\bSHOPIFY\b/i, merchant: 'Shopify', category: C.software },
  { pattern: /\bSQUARESPACE\b/i, merchant: 'Squarespace', category: C.software },
  { pattern: /\bWIX\b/i, merchant: 'Wix', category: C.software },
  { pattern: /\bCANVA\b/i, merchant: 'Canva', category: C.software },
  { pattern: /\bOPENAI\b/i, merchant: 'OpenAI', category: C.software },
  { pattern: /\b1PASSWORD\b|ONEPASSWORD/i, merchant: '1Password', category: C.software },
  { pattern: /\bGOOGLE\s*(ADS|ADWORDS)/i, merchant: 'Google Ads', category: C.advertising },
  { pattern: /\bFACEBOOK|META\s*ADS|FB\s*ADS/i, merchant: 'Meta Ads', category: C.advertising },
  { pattern: /\bLINKEDIN/i, merchant: 'LinkedIn', category: C.advertising },
  { pattern: /\bMAILCHIMP\b/i, merchant: 'Mailchimp', category: C.advertising },
  { pattern: /\bWALMART\b/i, merchant: 'Walmart', category: C.groceries },
  { pattern: /\bTARGET\b/i, merchant: 'Target', category: C.groceries },
  { pattern: /\bCOSTCO\b/i, merchant: 'Costco', category: C.groceries },
  { pattern: /\bWHOLE\s*FOODS/i, merchant: 'Whole Foods', category: C.groceries },
  { pattern: /\bTRADER\s*JOE/i, merchant: "Trader Joe's", category: C.groceries },
  { pattern: /\bKROGER\b/i, merchant: 'Kroger', category: C.groceries },
  { pattern: /\bALDI\b/i, merchant: 'ALDI', category: C.groceries },
  { pattern: /\bSAFEWAY\b/i, merchant: 'Safeway', category: C.groceries },
  { pattern: /\bPUBLIX\b/i, merchant: 'Publix', category: C.groceries },
  { pattern: /\bFEDEX\b|FEDERAL\s*EXPRESS/i, merchant: 'FedEx', category: C.shipping },
  { pattern: /\bUPS\b/i, merchant: 'UPS', category: C.shipping },
  { pattern: /\bUSPS\b/i, merchant: 'USPS', category: C.shipping },
  { pattern: /\bDHL\b/i, merchant: 'DHL', category: C.shipping },
  { pattern: /\bAIRBNB\b/i, merchant: 'Airbnb', category: C.travel },
  { pattern: /\bBOOKING\.COM/i, merchant: 'Booking.com', category: C.travel },
  { pattern: /\bEXPEDIA\b/i, merchant: 'Expedia', category: C.travel },
  { pattern: /\bSOUTHWEST\b/i, merchant: 'Southwest Airlines', category: C.travel },
  { pattern: /\bDELTA\s*AIR/i, merchant: 'Delta Airlines', category: C.travel },
  { pattern: /\bUNITED\s*AIR/i, merchant: 'United Airlines', category: C.travel },
  { pattern: /\bAMERICAN\s*AIR/i, merchant: 'American Airlines', category: C.travel },
  { pattern: /\bNETFLIX\b/i, merchant: 'Netflix', category: C.subscriptions },
  { pattern: /\bSPOTIFY\b/i, merchant: 'Spotify', category: C.subscriptions },
  { pattern: /\bHULU\b/i, merchant: 'Hulu', category: C.subscriptions },
  { pattern: /\bDISNEY/i, merchant: 'Disney+', category: C.subscriptions },
  { pattern: /\bCOMCAST\b|XFINITY/i, merchant: 'Comcast/Xfinity', category: C.utilities },
  { pattern: /\bVERIZON\b/i, merchant: 'Verizon', category: C.utilities },
  { pattern: /\bT-?MOBILE\b/i, merchant: 'T-Mobile', category: C.utilities },
  { pattern: /\bGEICO\b/i, merchant: 'GEICO', category: C.insurance },
  { pattern: /\bSTATE\s*FARM/i, merchant: 'State Farm', category: C.insurance },
  { pattern: /\bPROGRESSIVE\b/i, merchant: 'Progressive', category: C.insurance },
  { pattern: /\bGUSTO\b/i, merchant: 'Gusto', category: C.payroll },
  { pattern: /\bADP\b/i, merchant: 'ADP', category: C.payroll },
  { pattern: /\bPAYCHEX\b/i, merchant: 'Paychex', category: C.payroll },
  { pattern: /\bRIPPLING\b/i, merchant: 'Rippling', category: C.payroll },
];

export function matchMerchant(text: string): MerchantPattern | undefined {
  for (const mp of MERCHANT_PATTERNS) {
    if (mp.pattern.test(text)) {
      return mp;
    }
  }
  return undefined;
}
